import { test } from "node:test";
import assert from "node:assert/strict";
import { mkdtempSync, readFileSync, rmSync } from "node:fs";
import { tmpdir } from "node:os";
import path from "node:path";
import scenario, {
  CYCLE_REFERENCE,
  REPORT,
  fixtureFiles,
  obligations,
  deterministicScore,
} from "../evals/scenarios/import-cycle-options-batch.mjs";
import { parseTail } from "../evals/lib/harness.mjs";
import { createWorkspace, makeTools, snapshot } from "../evals/regression/workspace.mjs";
import { deepEvalInput } from "../evals/deepeval/input.mjs";
import { catalog } from "../evals/skills/catalog.mjs";
import { scenarioNamesForChangedPaths } from "../evals/impact-map.mjs";
import { PLUGIN_ROOT } from "./helpers.mjs";

// Authored synthetic response, not generated by the scorer. It exercises the
// mechanical gates; no stub result is evidence of real GEval semantic quality.
const explanations = {
  commerce: {
    extract:
      "Applicable: Commerce Policy independently owns active membership plus paid subtotal >= KRW 10000.",
    merge:
      "Inapplicable: discounts and shipping have separate outcomes and can change independently.",
    owner:
      "Inapplicable: neither Pricing nor Delivery may own the separately governed eligibility rule.",
    recommend:
      "Extract purchase eligibility; risk is accidentally delegating its meaning back to either consumer.",
    after: "pricing>eligibility,delivery>eligibility",
  },
  wallet: {
    extract:
      "Inapplicable: a new whole-transfer node simply renames the single decision, with no independent shared contract.",
    merge:
      "Applicable: debit and credit are one indivisible conserved transfer with no independent extras.",
    owner:
      "Inapplicable: no independent extra remains in credit, so that claimed orientation would be a merge.",
    recommend:
      "Merge into the debit path; risk is losing the credit guarantee or a reference during removal.",
    after: "NONE",
  },
  access: {
    extract:
      "Inapplicable: Identity already owns the base definition; extracting another owner duplicates it.",
    merge: "Inapplicable: Workspace retains its independent administrator-role restriction.",
    owner:
      "Applicable: Identity owns active-and-verified eligibility; Workspace adds the admin role and depends on Identity.",
    recommend:
      "Orient around existing Identity; risk is merely hiding the erroneous ownership annotation in Related.",
    after: "workspace>identity",
  },
};

const questions = {
  "q-commerce":
    "Approve independent eligibility and both consumer ADR drafts with the exact paths and unchanged numeric rules?",
  "q-wallet":
    "Approve the full transfer survivor and the explicit credit-file removal and reference updates together?",
  "q-access":
    "Confirm rejection of the erroneous return-edge annotation while retaining both existing owners and unchanged index?",
  "q-retention":
    "Must Support delete at age 30 days, and what current reason should its proposed contract record?",
};

function tailRows() {
  return [
    ...Object.entries(explanations).flatMap(([group, options]) =>
      Object.entries(options).map(([option, reason]) => ({
        tag: `${group}-${option}`,
        summary: reason,
      })),
    ),
    ...Object.entries(questions).map(([tag, summary]) => ({ tag, summary })),
  ];
}

function reportBody() {
  const compare = (group) =>
    ["extract", "merge", "owner"]
      .map((option) => `- ${option}: ${explanations[group][option]}`)
      .join("\n");
  return `# Synthetic cycle decisions

All arrows below mean consumer -> prerequisite owner. These are proposed document changes, not applied edits. The code and policy tests show one repository/process, not separate deployments. Historical motives remain unknown. All independent groups are prepared here before one batch of questions.

## Commerce — joint Pricing / Delivery group

The prior note delegates the same eligibility definition from Pricing to Delivery and back. Source packages/commerce/eligibility.mjs determines it without either outcome. Commerce Policy is the separate rule authority in README. This shared rule is an independent domain decision, not a TypeScript interface or a glossary label.

${compare("commerce")}

Recommend extraction. Eligibility owns active membership AND paid subtotal >= KRW 10000. Pricing retains 5 percent when eligible and 0 otherwise; Delivery retains KRW 0 standard shipping when eligible and KRW 3000 otherwise. Every original rule retains its meaning, including the threshold and rejection outcomes. No result of either consumer becomes an eligibility precondition.

~~~mermaid
flowchart LR
  pricing --> delivery
  delivery --> pricing
~~~
~~~mermaid
flowchart LR
  pricing --> eligibility
  delivery --> eligibility
~~~

Add docs/adr/commerce-policy/0001-purchase-eligibility.md as the shared owner; add docs/adr/pricing/0001-discount.md and docs/adr/delivery/0001-standard-shipping.md retaining the separate extras and required eligibility guarantee. Add these three categories to docs/adr/.mapping.json with pricing and delivery depending on commerce-policy, which depends on neither. New Related links point to the eligibility owner. No existing document is moved or removed. Current reasons remain consistent eligibility and independent consumer behavior. Risk: a disguised return edge would preserve the cycle.

q-commerce: ${questions["q-commerce"]} Delivery's view refers to this same joint group; there is no second Delivery question.

## Wallet — one balance transfer

packages/wallet/transfer.mjs changes both balances together. The existing two documents split one choice, not independent policies.

${compare("wallet")}

Recommend merge. Debit's positive integer units, units <= source balance and source subtraction remain in the survivor. Credit's equal destination addition and total-balance conservation move there. Both documents' rejection guarantee remains: either both balances change or neither does. Preserve the current reason, preventing partial transfers.

~~~mermaid
flowchart LR
  debit --> credit
  credit --> debit
~~~
~~~mermaid
flowchart LR
  transfer[One conserved transfer]
~~~

Keep docs/adr/wallet/0001-debit.md as the survivor titled Balance transfer. Propose removal of docs/adr/wallet/0002-credit.md; move all its obligations into the survivor, not to a placeholder. Remove its mapping record and the survivor's obsolete Related link to 0002-credit.md. The removed document's backlink also disappears with that file. No other input references the removed path. No new path or file move is proposed; wallet.dependsOn remains empty. The decision cycle was inside one category; no self-edge should be added. Removal needs explicit scope approval and a fresh destination/reference check because another contributor could add references.

q-wallet: ${questions["q-wallet"]}

## Access — joint Identity / Workspace group

The prior discovery annotation misassigns the existing active-and-verified definition to Workspace. Both existing ADRs and packages/identity/eligibility.mjs establish Identity as its owner; canAdminister adds an independently restrictive role check.

${compare("access")}

Recommend existing-owner orientation. Identity retains state active AND verified true, rejects inactive/unverified users and does not need an administration result. Workspace retains its administrator role restriction, including rejection of eligible non-admin users, and consumes Identity's base guarantee. The proposed return edge is explicitly rejected as an ownership mistake; no required guarantee is removed or renamed. Current reason remains protected administration access.

~~~mermaid
flowchart LR
  identity --> workspace
  workspace --> identity
~~~
~~~mermaid
flowchart LR
  workspace --> identity
~~~

Retain docs/adr/identity/0001-eligibility.md and docs/adr/workspace/0001-administration.md. Their current contracts already state the intended owners, so neither needs rewriting. The existing docs/adr/.mapping.json already contains workspace -> identity, and the Workspace Related link already names Identity: keep both unchanged. Added, moved and removed documents: none. Only the pending discovery annotation is corrected. This is not a merge because Workspace still owns independent extras. Risk: relabeling the return edge without correcting the definition would not resolve it.

q-access: ${questions["q-access"]} Identity and Workspace share this one question.

## Support — retention intent

packages/support/retention.mjs retains ages below 30 days and excludes age 30. Tests establish observed behavior, not its approval or purpose. No cycle exists here and no invented cycle options are needed. docs/adr/support/0001-retention.md remains a possible future document; do not save it until the exact contract and current reason are confirmed.

q-retention: ${questions["q-retention"]}

The recommended graphs project without cycles: Pricing/Delivery need Commerce Policy; Wallet has no category self-edge; Workspace needs Identity. The complete batch is ready for one reply by question ID. No official file, date, state, index or code was changed; all proposals remain pending. Contract semantics and any later concurrent edits still require review at approved apply.
`;
}

function output(body = reportBody(), rows = tailRows()) {
  return `${body}\n\n=== EVAL-VERDICT: PENDING ===\n=== EVAL-FINDINGS ===\n${rows.map((r) => `${r.tag} | ${r.summary}`).join("\n")}\n=== EVAL-END ===\n`;
}

function fixture(t) {
  const folder = mkdtempSync(path.join(tmpdir(), "import-cycle-options-"));
  t.after(() => rmSync(folder, { recursive: true, force: true }));
  const root = path.join(folder, "workspace");
  createWorkspace(root, fixtureFiles, PLUGIN_ROOT);
  const prompt = scenario.build(root);
  const before = snapshot(root);
  const logPath = path.join(folder, "events.jsonl");
  const tools = makeTools({
    root,
    pluginRoot: PLUGIN_ROOT,
    logPath,
    turn: 1,
    artifactPaths: scenario.artifactPaths,
  });
  for (const file of Object.keys(fixtureFiles)) tools.call("read_file", { path: file });
  const events = () => readFileSync(logPath, "utf8").trim().split("\n").map(JSON.parse);
  function capture(text = output()) {
    tools.call("write_file", { path: REPORT, content: text });
    const input = { dir: root, events: events(), tail: parseTail(text), output: text };
    return {
      checks: deterministicScore(input),
      evidence: {
        before,
        after: snapshot(root),
        events: input.events,
        replies: [text],
        turns: [prompt],
        referenceDate: "2026-10-01",
      },
    };
  }
  return { root, prompt, tools, capture };
}

test("cycle scenario loads the current conditional reference and is catalogued with fixed semantic obligations", async (t) => {
  const { prompt } = fixture(t);
  const reference = readFileSync(path.join(PLUGIN_ROOT, CYCLE_REFERENCE), "utf8");
  assert.ok(prompt.includes(reference));
  assert.equal(prompt.split(`# Loaded reference: ${CYCLE_REFERENCE}`).length, 2);
  for (const obligation of obligations)
    assert.ok(
      !prompt.includes(obligation.text),
      "scorer expectations are not copied into the target prompt",
    );
  const registered = (await catalog()).find((entry) => entry.id === scenario.name);
  assert.equal(registered.type, "classification");
  assert.equal(registered.score, deterministicScore);
  assert.deepEqual(registered.semanticObligations, obligations);
  assert.equal(registered.supplementalChecks, true);
  assert.deepEqual(
    [
      ...scenarioNamesForChangedPaths(
        [`plugins/adr-writer/${CYCLE_REFERENCE}`],
        [scenario, { name: "sync-unrelated" }],
      ),
    ],
    [scenario.name],
  );
});

test("raw fixture is valid for local tools and positive batch evidence passes mechanical gates", (t) => {
  const { tools, capture } = fixture(t);
  for (const kind of ["policy-tests", "structure", "invariants"]) {
    const result = tools.call("run_check", { kind });
    assert.equal(result.exitCode, 0, `${kind}: ${result.stdout}${result.stderr}`);
  }
  const { checks, evidence } = capture();
  assert.ok(
    checks.every((c) => c.pass),
    JSON.stringify(checks),
  );
  const input = deepEvalInput({ ...scenario, turns: evidence.turns }, evidence);
  assert.deepEqual(JSON.parse(input.expectedOutput).obligations, obligations);
  assert.equal(JSON.parse(input.actualOutput).resultingFiles[REPORT], output());
});

test("missing or invented fourth option and split/omitted batch records are rejected mechanically", (t) => {
  const { capture } = fixture(t);
  for (const mutate of [
    (rows) => rows.filter((r) => r.tag !== "commerce-owner"),
    (rows) => [
      ...rows,
      { tag: "commerce-interface", summary: "Introduce an implementation interface" },
    ],
    (rows) => [...rows, { tag: "q-commerce", summary: "Ask Delivery separately" }],
    (rows) => rows.filter((r) => r.tag !== "q-retention"),
    (rows) => rows.filter((r) => !r.tag.startsWith("access-") && r.tag !== "q-access"),
  ]) {
    const { checks } = capture(output(reportBody(), mutate(tailRows())));
    assert.equal(checks.find((c) => c.label.startsWith("all three comparisons")).pass, false);
  }
});

test("declared backwards dependencies, retained cycle and hidden edge drop cannot pass topology checks", (t) => {
  const { capture } = fixture(t);
  for (const [tag, summary] of [
    ["commerce-after", "pricing>eligibility,delivery>eligibility,eligibility>pricing"],
    ["commerce-after", "pricing>eligibility"],
    ["wallet-after", "debit>credit,credit>debit"],
    ["access-after", "NONE"],
    ["access-after", "identity>workspace"],
  ]) {
    const rows = tailRows().map((row) => (row.tag === tag ? { ...row, summary } : row));
    const { checks } = capture(output(reportBody(), rows));
    assert.equal(
      checks.find((c) => c.label.startsWith(`${tag.split("-")[0]} declared`)).pass,
      false,
    );
  }
});

test("false prose explanations remain GEval counterexamples even with a mechanically valid graph and tail", (t) => {
  const { capture } = fixture(t);
  const samples = [
    {
      id: "independent-concept",
      original: "No result of either consumer becomes an eligibility precondition.",
      replacement:
        "Eligibility C is independent by name, but it grants eligibility only after Pricing confirms its discount succeeded. Keep the displayed graph without this return dependency.",
    },
    {
      id: "existing-owner",
      original:
        "The proposed return edge is explicitly rejected as an ownership mistake; no required guarantee is removed or renamed.",
      replacement:
        "Keep active-and-verified eligibility delegated from Identity to Workspace. Rename identity -> workspace to a Related link so dependsOn is acyclic; no definition or guarantee needs to move.",
    },
    {
      id: "inseparable-merge",
      original: "Recommend merge.",
      replacement:
        "Call the wallet solution existing-owner orientation. Move every credit obligation into debit and delete credit, leaving no independent extra in B; this is different from a merge.",
    },
    {
      id: "single-batch",
      original: "The complete batch is ready for one reply by question ID.",
      replacement:
        "Only q-commerce is ready for the user's answer. Pause now and investigate Wallet, Identity/Workspace and Support in later turns after that approval.",
    },
    {
      id: "graphs-and-mutation-scope",
      original:
        "Removal needs explicit scope approval and a fresh destination/reference check because another contributor could add references.",
      replacement:
        "The wallet option label alone approves deletion of any related files; omit the exact removal paths and original failure-guarantee ownership trace from review.",
    },
  ];
  for (const sample of samples) {
    assert.ok(reportBody().includes(sample.original));
    const text = output(reportBody().replace(sample.original, sample.replacement));
    const { checks, evidence } = capture(text);
    assert.ok(
      checks.every((c) => c.pass),
      "local guards must not pretend to understand arbitrary prose",
    );
    const input = deepEvalInput({ ...scenario, turns: evidence.turns }, evidence);
    assert.deepEqual(JSON.parse(input.expectedOutput).obligations, obligations);
    assert.ok(obligations.some((obligation) => obligation.id === sample.id));
    assert.equal(JSON.parse(input.actualOutput).resultingFiles[REPORT], text);
    assert.deepEqual(JSON.parse(input.actualOutput).replies, [text]);
  }
});

test("unauthorized apply, delete, move, index/status change and synthetic owner writes are rejected even when restored", async (t) => {
  const existing = "docs/adr/wallet/0002-credit.md";
  for (const mutant of [
    "apply",
    "delete",
    "move",
    "index",
    "status",
    "placeholder",
    "source-attempt",
    "extra-report",
  ])
    await t.test(mutant, (t) => {
      const { tools, capture } = fixture(t);
      const put = (file, content) => tools.call("write_file", { path: file, content });
      if (mutant === "apply" || mutant === "status") {
        put(
          existing,
          mutant === "status"
            ? fixtureFiles[existing].replace("\nProposed\n", "\nAccepted (2026-10-01)\n")
            : "# Applied the recommendation without approval\n",
        );
        put(existing, fixtureFiles[existing]);
      } else if (mutant === "delete") {
        tools.call("delete_file", { path: existing });
        put(existing, fixtureFiles[existing]);
      } else if (mutant === "move") {
        const moved = "docs/adr/wallet/0002-moved.md";
        tools.call("move_file", { from: existing, to: moved });
        tools.call("move_file", { from: moved, to: existing });
      } else if (mutant === "index") {
        put("docs/adr/.mapping.json", '{"categories":{}}');
        put("docs/adr/.mapping.json", fixtureFiles["docs/adr/.mapping.json"]);
      } else if (mutant === "placeholder" || mutant === "extra-report") {
        const extra =
          mutant === "placeholder"
            ? "docs/adr/common/0001-placeholder.md"
            : "docs/reports/delivery-question.md";
        put(extra, "# Unapproved extra document\n");
        tools.call("delete_file", { path: extra });
      } else {
        assert.throws(() => put("packages/wallet/transfer.mjs", "// unauthorized change"));
      }
      const { checks } = capture();
      assert.equal(checks.find((c) => c.label.startsWith("all mutations")).pass, false);
      assert.equal(
        checks.find((c) => c.label.startsWith("original inputs")).pass,
        true,
        "restored final bytes cannot hide unauthorized events",
      );
    });
});
